"""add_tool_executions_table

Revision ID: d483646e26ae
Revises:
Create Date: 2025-10-30 19:07:02.255155

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d483646e26ae"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create tool_executions table for observability
    op.create_table(
        "tool_executions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_type", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("input_params", sa.JSON(), nullable=True),
        sa.Column("output_data", sa.JSON(), nullable=True),
        sa.Column("transport", sa.String(length=20), nullable=False),
        sa.Column("domain", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_executions")),
    )
    op.create_index(
        op.f("ix_tool_executions_correlation_id"),
        "tool_executions",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        "ix_tool_executions_correlation_session",
        "tool_executions",
        ["correlation_id", "session_id"],
        unique=False,
    )
    op.create_index(
        "ix_tool_executions_domain_time", "tool_executions", ["domain", "started_at"], unique=False
    )
    op.create_index(
        op.f("ix_tool_executions_session_id"), "tool_executions", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_tool_executions_started_at"), "tool_executions", ["started_at"], unique=False
    )
    op.create_index(op.f("ix_tool_executions_status"), "tool_executions", ["status"], unique=False)
    op.create_index(
        op.f("ix_tool_executions_tool_name"), "tool_executions", ["tool_name"], unique=False
    )
    op.create_index(
        "ix_tool_executions_tool_status_time",
        "tool_executions",
        ["tool_name", "status", "started_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tool_executions table
    op.drop_index("ix_tool_executions_tool_status_time", table_name="tool_executions")
    op.drop_index(op.f("ix_tool_executions_tool_name"), table_name="tool_executions")
    op.drop_index(op.f("ix_tool_executions_status"), table_name="tool_executions")
    op.drop_index(op.f("ix_tool_executions_started_at"), table_name="tool_executions")
    op.drop_index(op.f("ix_tool_executions_session_id"), table_name="tool_executions")
    op.drop_index("ix_tool_executions_domain_time", table_name="tool_executions")
    op.drop_index("ix_tool_executions_correlation_session", table_name="tool_executions")
    op.drop_index(op.f("ix_tool_executions_correlation_id"), table_name="tool_executions")
    op.drop_table("tool_executions")
    # ### end Alembic commands ###
